name: OCR Integration CI

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'Dockerfile'
  pull_request:
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'Dockerfile'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system dependencies for OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential python3 libvips-dev libvips-tools poppler-utils tesseract-ocr

      - name: Install dependencies
        run: npm ci
      - name: Rebuild sharp
        run: npm rebuild sharp --unsafe-perm

      - name: Ensure tesseract Turkish traineddata
        run: |
          mkdir -p /usr/share/tessdata || true
          if [ ! -f /usr/share/tessdata/tur.traineddata ]; then
            echo "Downloading tur traineddata"
            sudo apt-get install -y tesseract-ocr-tur || true
          fi

      - name: Run CI OCR helper using local tesseract CLI
        run: |
          chmod +x scripts/ci-local-ocr.sh
          ./scripts/ci-local-ocr.sh "$GITHUB_WORKSPACE/pmyo-sartname.pdf" tmp/ci-ocr || true

      - name: Upload OCR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ocr-output
          path: tmp/ci-ocr
